### ISSUE TITLE
documentation about funfuzz

### ISSUE THREAD

**Issue by huangshiyou** [MozillaSecurity/funfuzz#196]
Howdy!

May I know what .fuzzmanagerconf is for and how to configure this? Also, is there any documentation about the code?

**Comment by nth10sd** [comment]
It's for reporting to [FuzzManager](https://github.com/MozillaSecurity/FuzzManager) - you can find documentation there too. FuzzManager is also listed in `requirements.txt`.

**Comment by huangshiyou** [comment]
Thanks for your reply. Is it possible to just use funfuzz without running fuzzmanager?

**Comment by nth10sd** [comment]
Unlikely. It reports to FuzzManager, it extracts known crashes/stacks from FuzzManager, duplicate detection is via FuzzManager.

Many years ago it used to work without, when FuzzManager was nascent, but I've long since removed local code related to the functionalities above, once it matured.

You can run FuzzManager locally and set your .fuzzmanagerconf to report to the localhost FuzzManager instance, it *should* still work.

**Comment by huangshiyou** [comment]
I see. Thanks. What the server host and port should be if the FuzzManager runs remotely (I assume it runs as a service provided by Mozilla)

**Comment by nth10sd** [comment]
Nope, Mozilla does not provide this as a service, you are free to create your own.

**Comment by huangshiyou** [comment]
Ok. Thanks. But this looks not very convenient.
