### ISSUE TITLE
[compileShell] Add support for building Windows js shell with clang

### ISSUE THREAD

**Issue by rforbes** [MozillaSecurity/funfuzz#24]
Allow compileshell.py to build windows jsshell with clang and asan.

**Comment by nth10sd** [comment]
I'll take this, will need @rforbes help to test.

**Comment by nth10sd** [comment]
Thanks to initial build instructions from @rforbes - I eventually got a 32-bit and 64-bit js shell compiling with clang off m-c rev 8a7cc8b7aa55.

I used:

* LLVM 3.7.1
 * For 32-bit: http://llvm.org/releases/3.7.1/LLVM-3.7.1-win32.exe
 * For 64-bit: http://llvm.org/releases/3.7.1/LLVM-3.7.1-win64.exe
* Made some changes to MozillaBuild (local for now)
* Some upcoming changes needed to compileShell (local for now)
 * We might just add --build-with-clang to all platforms. It will be:
  * On by default for Mac
  * Off by default for Linux (since the default is GCC)
  * Off by default for Windows (since the default is MSVC)

Compiling with ASan turned on still fails - we should separate that into another issue.

I also found that compiling with --without-intl-api drops the compile time: (also to be separated)
* Windows 10: ~1000s (~17mins) down to ~200s (~3.5mins)
 * on an Intel Core i5-6500 on Windows 10 with 16GB RAM and an SSD.
* Mac OS X 10.11: ~350s (~6mins) down to ~120s (~2mins)
 * on a MacBook Pro11,3 Core i7 with 16GB RAM and an SSD.

**Comment by nth10sd** [comment]
Support for --without-intl-api was added in buildOptions.py in rev d2c6e99.

Chatted with Jesse in-person and we agreed that the best way forward is to first add --build-with-clang, then --build-with-asan for all platforms.

**Comment by nth10sd** [comment]
I've moved my MozillaBuild changes to b.m.o:

https://bugzilla.mozilla.org/show_bug.cgi?id=1238251

**Comment by nth10sd** [comment]
I've got preliminary support for --build-with-clang across all platforms landed via rev 8e1ddd61622be4a3ae760d0771b23ba03e013065, but this is still disabled by default (buildOptions) in rev cea9ff1718502cb4ebf3b31e446cfcebf4bc1035.

**Comment by nth10sd** [comment]
Due to an ever-moving target, LLVM support on Windows for Gecko still isn't stable yet. (It seems the current plan is to aim for LLVM 3.9.0 or thereafter)

Currently as of funfuzz rev e1cd151 we support building with LLVM up till m-c rev e1280633aeae (end-Jan 2016).

**Comment by nth10sd** [comment]
This is completed for now, we can open a new issue for when Clang Windows builds are finally stable.
