### ISSUE TITLE
Where is reduced test case(domfuzz)?

### ISSUE THREAD

**Issue by ghost** [MozillaSecurity/funfuzz#39]
When domfuzz finds Assertion failure, it will send an report to FuzzManager. In that report, I can see "Test Status" column witch contains numbers. 

Example ---> Q9 362778

I think that number is reduced test cace's file number, but I can not find that test cace file...:(  

When I go to wptm and lith tmp folders, I can find many html files(e.g. boring.html, interesting.html, splice-reduced.html and etc). I checked these files...but source code lines are over 9000.... I think these files are not I am looking for.

Even if I can find a bug, it is meaningless if I can not reproduce that bug... 

I used this command.

funfuzz/util/multi.py 6 funfuzz/dom/automation/loopdomfuzz.py build

I changed 8 --> 6 because I wanted to know what will happen if I changed this number. Is this the route cause??

**Comment by jruderman** [comment]
> funfuzz/util/multi.py 6 funfuzz/dom/automation/loopdomfuzz.py build

Here, 6 is the number of instances of loopdomfuzz.py to launch. On machines with sufficient RAM, I launch as many instances as I have logical cores.

> Q9 362778

This means a testcase of "size 362778" and "quality 9" was uploaded with the crash. This testcase should be available in the FuzzManager web app by clicking the entry and scrolling past stderr. (You shouldn't have to dig through the temp dirs to find it.)

Only "Q0" testcases are fully reduced. Other quality scores are assigned in loopdomfuzz.py for various ways that the code fails to reproduce or reduce the testcase. Personally, I ignore everything that isn't Q0, because trying to fix things up manually is a pain and not always successful.

**Comment by kazenomamani210** [comment]
Thank you for reply. I could find test case:) 

I looked Q0 entry. "Test status" column indicated....

Q0 312181 

When I go to above entry, I can see test case which is really long html code. File size is"312181." This is big, isn't it? I thought my fuzzer failed to reduce test case...

My question is... How do you determine crash's route cause from huge html file?

I'm sorry for asking many questions. It is impossible for me to understand funfuzz system without help. I appreciate your kindness.

**Comment by jruderman** [comment]
>  When I go to above entry, I can see test case which is really long html code. File size is"312181." This is big, isn't it? I thought my fuzzer failed to reduce test case...

The total file size is large, but the section at the top with the generated code should be reduced. It's the section between "DDBEGIN" and "DDEND". You can use serializeFuzzCommands() or the other tricks in https://github.com/MozillaSecurity/funfuzz/blob/master/dom/reducing-testcases.md to turn it into a proper reduced testcase with no fuzzer left over.

>  I'm sorry for asking many questions. It is impossible for me to understand funfuzz system without help. I appreciate your kindness.

Thanks for taking the time to point out what's confusing. I'll try to make things less confusing :)

>  p.s. I attached a picture. When I see ID 6 and ID 7, these "Assertion failure" messages are the same. I guess ID 7 is reduce test case from ID 6. Am I correct?

I think it means it hit the bug twice, and one of the times it was able to make a reduced testcase but the other time it was not. You can compare the generated parts of the testcase to confirm that one is not a subset of the other.

**Comment by kazenomamani210** [comment]
I could found "DDBEGIN" and "DDEND." So I am on the right path.

There are "fuzzCommands.push" messages between "DDBEGIN" and "DDEND."

My next question is... how to use it? Obviously, these codes are not html or javascript code.


I read a documentation, but I couldn't understand how to generate html test case from "fuzzCommands.push" messages. 

Probably, I need to make an html file. Like this...

----------------------------

<script>
// DDBEGIN

fuzzCommands.push messages

// DDEND
</script>

<script>

Is this the space for options? e.g. serializeHTML() 

</script>

----------------------------

After I made that html file, I will load to that file to firefox. Am I correct? Do I need to use another tool?

Please teach me what commands should I use.

**Comment by jruderman** [comment]
To use a function like serializeHTML or serializeXML, add a new line below the other fuzzCommands.push lines:

    fuzzCommands.push({ note:   5110, fun: function() { dumpln(serializeHTML()); } });

When you load the testcase, it will do all the same things and then print equivalent HTML markup to stdout. This works for many layout testcases, but sometimes you'll have to experiment with putting it a few lines above and leaving the last few lines as dynamic changes.

serializeFuzzCommands, on the other hand, is special and can be called from the top level.

**Comment by kazenomamani210** [comment]
After I made the testcase, I use command...

lithium.py domInteresting.py build testcase.html 

or 

domInteresting.py build testcase.html

An error message will appear...

-----error message------

JavaScript error: file:///home/kaze/testcase.html, line 8: ReferenceError: fuzzCommands is not defined

------------------------------

My question is how to load testcase to firefox? I am going to attach my testcase, please check it. I can not attach html file on github, so I am going to attach  testcase.txt format instead of testcase.html.

[testcase.txt](https://github.com/MozillaSecurity/funfuzz/files/300852/testcase.txt)


It would be really nice if there is an example testcase file...

I feel guilty for asking many questions...:( I am sorry.

**Comment by jruderman** [comment]
What you have looks good, but there should be a lot more in the file that loopdomfuzz.py creates. If you have to create it by hand, paste in most of your wtmp*/fuzzer-combined.js (except for the part of fuzzer-combined.js marked "splice" at the top).

**Comment by kazenomamani210** [comment]
How did you get clean html test case like this?

https://bug366012.bugzilla.mozilla.org/attachment.cgi?id=250556

I am struggling with getting html test case...:(




Loading this file displays "Assertion failure." Please change testcase.txt --> testcase.html.

[testcase.txt](https://github.com/MozillaSecurity/funfuzz/files/304937/testcase.txt)

I got this testcase file from FuzzManager web app by clicking the entry and scrolling past stderr.(Testcase)


I used command...

lithium.py domInteresting.py build testcase.html

or

domInteresting.py build testcase.html

---------------------------------------------

I experimented...

fuzzCommands.push({ note:   5110, fun: function() { dumpln(serializeHTML()); } });

but I can not get HTML markup to stdout. I put various places serializeHTML commands in order to test, but I only got open and close html tags. (inside html tags are empty)


I am getting better because of your advises.  Thank you so much.

**Comment by kazenomamani210** [comment]
Above testcase file, I put serializeHTML command before "// DDEND" line.

**Comment by kazenomamani210** [comment]
I am stupid... I was misunderstanding how to use serializeHTML().

In order to use serializeHTML(), I need to put arguments inside "()".  An example will be....

fuzzCommands.push({ note:   2410, fun: function() { dumpln(serializeHTML(o[481] = fuzzerWebIDL.rv)); } });

--------------------------------------------------

Just put...

fuzzCommands.push({ note: 5110, fun: function() { dumpln(serializeHTML()); } });

on testcase will not get nothing because... there is no argument.

Am I correct? If I am wrong please correct me.

**Comment by jruderman** [comment]
serializeHTML() can usually be used without arguments, but it's only useful for testcases that consist of DOM nodes and styles. This testcase creates an XPathExpression object, so it requires a different approach:

    fuzzCommands.push({ note:   1877, fun: function() { o[385] = document.createTextNode("\uDF58"); } });
    fuzzCommands.push({ note:   2401, fun: function() { fuzzerWebIDL.rv = o[4]["createExpression"](/*expression*/ " x", /*resolver*/ o[29] /* XPathNSResolver (callback interface) */); } });
    fuzzCommands.push({ note:   2410, fun: function() { o[481] = fuzzerWebIDL.rv; } });
    fuzzCommands.push({ note:   4555, fun: function() { fuzzerWebIDL.rv = o[481]["evaluate"](/*contextNode*/ o[385] /* Node (interface) */, /*type*/ 549755813887, /*result*/ o[194] /* no webidl info or found interface for: object*/); } });

For this kind of testcase, I'd make a sequence of transformations for clarity:

* Replace `o[4]` with `document`
* Rename `o[385]` as `text`
* Rename `o[481]` as `expr`
* Replace `o[194]` and `o[29]` with `undefined` or `null`
* Combine lines 2401 and 2410 into a single assignment, skipping `fuzzerWebIDL.rv`

And then try some simplifications:

* Try replacing `"\uDF58"` with `"x"`
* Try replacing `549755813887` with `0`

Once the contents of the funs make sense, you can copy them into a new file. serializeFuzzCommands() often simplifies this step.

https://github.com/MozillaSecurity/funfuzz/blob/master/dom/reducing-testcases.md#reducing-non-layout-testcases

**Comment by kazenomamani210** [comment]
My question 1:

If I replace 549755813887 with 0, "Assertion failure" will not happen. In this case, I should not replace with number with 0. Am I correct?

My question 2: 

In this testcase, after hitting "note:   4555", "Assertion failure" will happen.  After "Assertion failure" happend, rest of fuzzCommands.push will be ignored because I can not see "Playback: quit" message to stdout. 

So if "Assertion failure" happened before serializeFuzzCommands() , no html output to stdout. In this case, how can I get html testcase? I am going to attach my testcase.

-------------------------------------------------------------------------

fuzzCommands.push({ note:   1877, fun: function() { text = document.createTextNode("x"); } });

fuzzCommands.push({ note:   2401, fun: function() { fuzzerWebIDL.rv = document["createExpression"](/*expression*/ " x", /*resolver*/ null /* XPathNSResolver (callback interface) */); expr = fuzzerWebIDL.rv;} });

fuzzCommands.push({ note:   4555, fun: function() { fuzzerWebIDL.rv = expr["evaluate"](/*contextNode*/ text /* Node (interface) */, /*type*/ 549755813887, /*result*/ undefined /* no webidl info or found interface for: object*/); } });

fuzzCommands.push({ note:   5110, fun: function() { dumpln(serializeFuzzCommands()); } });

------------------------------------------------------------------------------

Changing /*type*/ 549755813887 ---> /*type*/ 0 will not cause "Assertion failure."

**Comment by kazenomamani210** [comment]
Understanding this tool is really hard because maybe I am stupid. Thank you for your kindness.

**Comment by jruderman** [comment]
We designed these tools for a combination of ourselves and machines, so it's helpful to have feedback about what's confusing. The more you understand the tools and JavaScript/DOM, the easier it becomes.

> If I replace 549755813887 with 0, "Assertion failure" will not happen. In this case, I should not replace with number with 0. Am I correct?

This is a useful discovery, and you are correct.

Optionally, you could try to figure out [how this value is used](https://dxr.mozilla.org/mozilla-central/source/dom/xslt/xpath/XPathExpression.cpp#163), or what the valid values are, or what the smallest crashing value is.

> In this testcase, after hitting "note: 4555", "Assertion failure" will happen. After "Assertion failure" happend, rest of fuzzCommands.push will be ignored because I can not see "Playback: quit" message to stdout.

> So if "Assertion failure" happened before serializeFuzzCommands() , no html output to stdout. In this case, how can I get html testcase?

The trick is to put serializeFuzzCommands() on a line of its own, not inside a fuzzCommands.push() line. All the fuzzCommands lines are evaluated after DOMContentLoaded or onload. This only works with serializeFuzzCommands(), not the other "serialize" functions.

But I'd recommend completely eliminating "fuzzerWebIDL.rv" from the fuzzCommands array first. Otherwise, you'll get an ReferenceError "fuzzerWebIDL is not defined" when you try to run the standalone testcase. On the 'note: 2401' line, you can combine the two assignments into one: { rv = longthing; expr = rv; } becomes {expr = longthing }. On the 'note:   4555' line, you can drop the assignment leaving an expression statement, so { rv = longthing; } just becomes { longthing; }

One final "simplification" is to turn `document["createExpression"]` into `document.createExpression`, etc. These are usually equivalent in JavaScript.

**Comment by kazenomamani210** [comment]
Could you please teach me what looks like after "put serializeFuzzCommands() on a line of its own, not inside a fuzzCommands.push() line"?

I tried many ways to use serializeFuzzCommands(), but I couldn't use it...:(

--------failed example-----------

`var serializeFuzzCommands = [];`

`serializeFuzzCommands.push({ note:   4555, fun: function() { expr["evaluate"](/*contextNode*/ text /* Node (interface) */, /*type*/ 549755813887, /*result*/ null /* no webidl info or found interface for: object*/); } });`

-----------------------------------------

I think it could be better if an example test case which a user can see entire FuzzCommands for generate html code on help page. Currently, there is only text explanation on help page.

https://github.com/MozillaSecurity/funfuzz/blob/master/dom/reducing-testcases.md#reducing-non-layout-testcases

 Just explaining by text is really hard to understand....:(

**Comment by jruderman** [comment]
Try a line with just `serializeFuzzCommands();`.

**Comment by kazenomamani210** [comment]
Finally I could get testcace html and reproduce "Assertion failure." I am really happy. Thank you so much for helping me.

Can I report this to Bugzilla? I think this is not a security issue and you have already known this.

**Comment by jruderman** [comment]
Yes, please report all bugs you find, not just security holes :)

**Comment by nth10sd** [comment]
DOMFuzz is about to be removed from the funfuzz repo (#108), and it is about to be placed on life support in another repo. Closing as I think we have helped with all here for now.
